`2024/09/06 10:35:05 `:apple:` `:wrench:` `willsturgeon

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -44,14 +44,17 @@ fi
 
 if [ "${1:+1}" ]; then :; else
   git pull
-  nixfmt .
+fi
 
-  # Check if anything changed, and, if so, remove the success/failure flag:
-  if [ -z "$(git status --porcelain)" ]; then :; else
-    rm -f .build-succeeded .build-failed
-  fi
+nixfmt .
 
-  # Push changes upstream with a W.I.P. note (wrench emoji):
+# Check if anything changed, and, if so, remove the success/failure flag:
+if [ -z "$(git status --porcelain)" ]; then :; else
+  rm -f .build-succeeded .build-failed
+fi
+
+# Push changes upstream with a W.I.P. note (wrench emoji):
+if [ "${1:+1}" ]; then :; else
   if [ -f .build-succeeded ]; then :; else
     if [ -f .build-failed ]; then :; else
       git add -A
@@ -63,10 +66,12 @@ fi
 
 # Update dependencies:
 nix flake update || : # rate limits!
-if [ "${1:+1}" ]; then :; else
-  git add -A
-  git commit -m "${COMMIT_PREFIX}"'` `:arrow_up:` `'"${USER}" || :
-  git push || :
+if [ -z "$(git status --porcelain)" ]; then :; else
+  if [ "${1:+1}" ]; then :; else
+    git add -A
+    git commit -m "${COMMIT_PREFIX}"'` `:arrow_up:` `'"${USER}" || :
+    git push || :
+  fi
 fi
 
 if [[ "${OS}" == "Linux" ]]; then
