`2024/09/06 10:08:05 Darwin `:wrench:

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -34,14 +34,18 @@ if [ "${1:+1}" ]; then :; else
   git pull
   nixfmt .
 
-  # Check if anything changed, and, if so,
-  # remove the success/failure flag (if it's there) and
-  # push the changes upstream with a WIP note:
+  # Check if anything changed, and, if so, remove the success/failure flag:
   if [ -z "$(git status --porcelain)" ]; then :; else
     rm -f .build-succeeded .build-failed
-    git add -A
-    git commit -m "${COMMIT_DATE}:wrench:" || :
-    git push || :
+  fi
+
+  # Push changes upstream with a W.I.P. note (wrench emoji):
+  if [ -f .build-succeeded ]; then :; else
+    if [ -f .build-failed ]; then :; else
+      git add -A
+      git commit -m "${COMMIT_DATE}:wrench:" || :
+      git push || :
+    fi
   fi
 fi
 
